package: gen_revpi_pkg: Validate upstream version argument
The upstream version regex is already there to parse the parts of the
version with sed. It can be reused to check if the upstream version is
valid in the first place.

Signed-off-by: Thomas Böhler <t.boehler@kunbus.com>

diff --git a/scripts/package/gen_revpi_pkg b/scripts/package/gen_revpi_pkg
--- a/scripts/package/gen_revpi_pkg
+++ b/scripts/package/gen_revpi_pkg
@@ -74,6 +74,11 @@ upstream_version=$1
 [ $VERBOSITY -gt 0 ] && set -x
 [ $VERBOSITY -gt 1 ] && EXTRA_MAKE_OPTS="KBUILD_VERBOSE=1"
 
+if ! expr "$upstream_version" : "$UPSTREAM_VERS_REGEX" >/dev/null; then
+	printf "Invalid upstream version\n" >&2
+	usage 1 >&2
+fi
+
 mainline_vers="$(printf "%s\n" "$upstream_version" \
 	| sed -e "s/$UPSTREAM_VERS_REGEX/\1/")"
 rt_vers="$(printf "%s\n" "$upstream_version" \
