package: mkdebian: force copyright generation
The debian/copyright file is copied from
scripts/package/debian/copyright and represents a generic copyright form
that is not in the standard DEP-5 form.

It should be possible to keep a debian/copyright while regenerating the
debian/ folder to have a custom debian/copyright that isn't removed.

The default debian/copyright file from scripts/package/debian/copyright
is used if the environment variable "FORCE_COPYRIGHT_GEN" is set.
No debian/copyright file is created by default and an error will be
thrown if at the end of the mkdebian script no debian/copyright file
exists.

Suggested-by: Philipp Rosenberger <p.rosenberger@kunbus.com>
Signed-off-by: Thomas Böhler <t.boehler@kunbus.com>

diff --git a/scripts/package/mkdebian b/scripts/package/mkdebian
--- a/scripts/package/mkdebian
+++ b/scripts/package/mkdebian
@@ -283,7 +283,16 @@ ARCH := ${ARCH}
 KERNELRELEASE := ${KERNELRELEASE}
 EOF
 
-cp "${srctree}/scripts/package/debian/copyright" debian/
+# Only generate a copyright file if none is present or it's explicitly wanted
+if [ "${FORCE_COPYRIGHT_GEN:+set}" ]; then
+	cp "${srctree}/scripts/package/debian/copyright" debian/
+fi
+
 cp "${srctree}/scripts/package/debian/rules" debian/
+
+if [ ! -f debian/copyright ]; then
+	echo "Error: No copyright file installed" >&2
+	exit 1
+fi
 
 exit 0
